### ISSUE TITLE
installing with apt 

### ISSUE THREAD

**Issue by Mahm0udMunir0** [Micro0x00/nucleitemp#1]
احنا يسطا ممكن ننزلها بطريقة احسن من كدا علشان اوقات بيحصل مشاكل في التثبيت 
وشكرا علي مجهودك 
sudo apt-get install nuclei

**Comment by lucky0luke** [comment]
يسطا issue ديه بتبقا معمولة لو فيه مشكله في اللي انا منزلها + انت بتكلم علي التول انا الاسكربت للتمبلتس
